In [10]:
import numpy as np

In [11]:
l1 = [i for i in range(1000000)]
l2 = [i**2 for i in range(1000000)]
import time
t1 = time.time()
l3 = l1+l2
t2 = time.time()
t2-t1

0.04905271530151367

In [13]:
n1= np.array(l1)
n2= np.array(l2)
t3 = time.time()
n3 = n1+n2
t4 = time.time()
t4-t3

0.006022930145263672

In [15]:
(t2-t1)/(t4-t3)

8.144327448341382

In [17]:
t1 = time.time()
l3 = [l1[i]*l2[i] for i in range(1000000)]
t2 = time.time()
t2-t1

0.19763851165771484

In [19]:
n1= np.array(l1)
n2= np.array(l2)
t3 = time.time()
n3 = n1*n2
t4 = time.time()
t4-t3

0.019862651824951172

In [21]:
(t2-t1)/(t4-t3)

9.950258072260233

# NumPy Array

In [36]:
a=np.array([1,2,3])

In [38]:
a

array([1, 2, 3])

In [40]:
np.zeros(2)

array([0., 0.])

In [52]:
np.zeros(10) #values will be in float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.eye(3) #creates an identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [58]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(2,6,2)

array([2, 4])

## Indexing and Slicing

In [63]:
data= np.array([1,2,3])

In [65]:
data[0]

1

In [67]:
data[-1]

3

In [71]:
data[-3:]

array([1, 2, 3])

In [75]:
data[-1::-1]

array([3, 2, 1])

# Multi-dimen Arrays

In [12]:
a = np.array([[11,2,3],[4,5,6],[7,8,9],[14,15,16]])

In [14]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [14, 15, 16]])

In [16]:
a<5

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
a[a<5]

array([2, 3, 4])

In [118]:
a[a>=6]

array([ 6,  7,  8,  9, 14, 15, 16])

In [120]:
a[a%2==0]

array([ 2,  4,  6,  8, 14, 16])

# multiple conditions

In [133]:
(a>2) & (a%2==0)

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [128]:
#multiple conditions
a[(a>2) & (a%2==0)]

array([ 4,  6,  8, 14, 16])

In [139]:
a[(a>2) | (a%2==0)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 14, 15, 16])

### Problems

In [142]:
data = np.array([1,2])

In [144]:
ones = np.ones(2)

In [146]:
data + ones

array([2., 3.])

In [148]:
data * ones

array([1., 2.])

In [152]:
a= np.array([1,2,3,4,5,6])

In [154]:
a.sum()

21

In [156]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [158]:
b= np.array([[1,2,3],[4,5,6],[7,8,9],[14,15,16]])

In [166]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [14, 15, 16]])

In [160]:
b.sum()

90

In [174]:
b.sum(axis=1)

array([ 6, 15, 24, 45])

In [178]:
b.sum(axis=0)

array([26, 30, 34])

## adding, removing and sorting

In [193]:
arr = np.array([7,8,9,5,1,4,5,2,6,3,5,4,1,2,2])

In [206]:
arr.sort()
arr

array([1, 1, 2, 2, 2, 3, 4, 4, 5, 5, 5, 6, 7, 8, 9])

In [208]:
np.sort(arr)

array([1, 1, 2, 2, 2, 3, 4, 4, 5, 5, 5, 6, 7, 8, 9])

In [199]:
arr.sum()

64

#### Concatenate

In [22]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [220]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [222]:
(a,b)

(array([1, 2, 3]), array([4, 5, 6]))

In [24]:
b= np.array([[1,2,3],[4,5,6],[7,8,9],[14,15,16]])

In [226]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [14, 15, 16]])

In [26]:
c= np.array([[14,22,3],[44,15,16],[7,8,9],[14,15,16]])

In [230]:
c

array([[14, 22,  3],
       [44, 15, 16],
       [ 7,  8,  9],
       [14, 15, 16]])

In [32]:
z=np.concatenate((b,c),axis=1)

In [34]:
z

array([[ 1,  2,  3, 14, 22,  3],
       [ 4,  5,  6, 44, 15, 16],
       [ 7,  8,  9,  7,  8,  9],
       [14, 15, 16, 14, 15, 16]])

In [254]:
z.shape

(8, 3)

In [246]:
c.shape

(4, 3)

In [248]:
z.ndim

2

In [260]:
z.size

24

## Broadcasting

In [263]:
d = np.array([1,2,3,3,3,6,4,8])

In [265]:
d * 1.2

array([1.2, 2.4, 3.6, 3.6, 3.6, 7.2, 4.8, 9.6])

In [267]:
d.min()

1

In [269]:
d.max()

8

In [271]:
d.sum()

30

In [273]:
d.ndim

1

In [275]:
d.shape

(8,)

In [277]:
a = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

In [279]:
a.shape

(2, 2, 3)

In [281]:
a.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [283]:
a.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [285]:
a.sum(axis=2)

array([[ 6, 15],
       [24, 33]])

In [291]:
a =np.random.randint(1,25,(4,5))

In [293]:
a

array([[22,  8, 20,  2, 20],
       [ 9, 20, 19, 17, 16],
       [ 2, 15, 22, 24,  8],
       [ 5, 18, 16, 24,  4]])

In [295]:
a[1:3,1:3]

array([[20, 19],
       [15, 22]])

## Matrices

In [6]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])

In [8]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
data[0,1]

2

In [12]:
data[1:3]

array([[3, 4],
       [5, 6]])

## Aggregation

In [16]:
a =np.random.randint(1,25,(4,5))

In [18]:
a

array([[21, 11, 23, 14, 20],
       [13,  9, 15, 12, 11],
       [20, 13,  5, 12, 19],
       [ 1, 20, 17, 11, 15]])

In [20]:
a[1:3,1:4]

array([[ 9, 15, 12],
       [13,  5, 12]])

### MMatrices addition, sub, Multipl

In [55]:
data=np.array([[1,5],[8,9]])
ones=np.array([[1,2],[4,5]])

In [57]:
data

array([[1, 5],
       [8, 9]])

In [59]:
ones

array([[1, 2],
       [4, 5]])

In [61]:
data + ones

array([[ 2,  7],
       [12, 14]])

In [63]:
data-ones

array([[0, 3],
       [4, 4]])

In [65]:
data*ones

array([[ 1, 10],
       [32, 45]])

## unique and count

In [68]:
from numpy import *

In [72]:
a = np.array([1,5,1,2,4,5,55,6,32,4,8,88,9,6,5,5,2,1])

In [147]:
np.unique(a)

array([ 1,  2,  4,  5,  6,  8,  9, 32, 55, 88])

In [90]:
data = np.array([[1,2,3],[4,5,6]])

In [92]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.transpose(data)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [98]:
np.shape(data)

(2, 3)

In [100]:
data.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
data.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [110]:
transpose(data)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [112]:
np.flip(data)

array([[6, 5, 4],
       [3, 2, 1]])

## Matrix Operations

In [42]:
n1=np.random.randint(1,5,(3,3))

In [133]:
n1

array([[1, 2, 4],
       [2, 3, 4],
       [4, 2, 3]])

In [125]:
# Calculate inverse of matrix

In [135]:
n1_inv = np.linalg.inv(n1)

In [137]:
n1_inv

array([[-0.09090909, -0.18181818,  0.36363636],
       [-0.90909091,  1.18181818, -0.36363636],
       [ 0.72727273, -0.54545455,  0.09090909]])

In [149]:
np.dot(n1,n1_inv)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 1.11022302e-16],
       [2.22044605e-16, 0.00000000e+00, 1.00000000e+00]])

In [36]:
n2=np.random.randint(1,10,(3,2))

In [153]:
n2

array([[1, 4],
       [9, 6],
       [2, 4]])

In [38]:
n3=np.random.randint(1,8,(2,3))

In [157]:
n3

array([[3, 1, 1],
       [5, 6, 6]])

In [46]:
np.dot(n1,n2)

array([[39, 75],
       [38, 68],
       [42, 77]])

In [44]:
np.dot(n2,n3)

array([[74, 57, 65],
       [89, 66, 80],
       [47, 38, 40]])

## Determinant of the Matrix

In [166]:
n1

array([[1, 2, 4],
       [2, 3, 4],
       [4, 2, 3]])

In [168]:
np.linalg.det(n1)

-10.999999999999996

## Flattering of a matrix

In [173]:
n1.flatten()

array([1, 2, 4, 2, 3, 4, 4, 2, 3])

In [175]:
type(n1)

numpy.ndarray

In [177]:
n1

array([[1, 2, 4],
       [2, 3, 4],
       [4, 2, 3]])